module VerifyExamples.Storage.Get0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#get: \n\n    empty\n        |> insert \"fruit\" (Value.string \"apple\")\n        |> get \"apple\"\n    --> Nothing" <|
        \() ->
            Expect.equal
                (Storage.empty
                    |> insert "fruit" (Value.string "apple")
                    |> get "apple"
                )
                Nothing
