module VerifyExamples.Storage.GetBool0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#getBool: \n\n    empty\n        |> insert \"is.cool\" (Value.bool True)\n        |> getBool \"is.cool\"\n    --> Just True" <|
        \() ->
            Expect.equal
                (Storage.empty
                    |> insert "is.cool" (Value.bool True)
                    |> getBool "is.cool"
                )
                (Just True)
