module VerifyExamples.Storage.GetFloat0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#getFloat: \n\n    empty\n        |> insert \"velocity\" (Value.float 1.6)\n        |> getFloat \"velocity\"\n    --> Just 1.6" <|
        \() ->
            Expect.equal
                (Storage.empty
                    |> insert "velocity" (Value.float 1.6)
                    |> getFloat "velocity"
                )
                (Just 1.6)
