module VerifyExamples.Storage.GetInt0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#getInt: \n\n    empty\n        |> insert \"moons\" (Value.int 1)\n        |> getFloat \"moons\"\n    --> Just 1" <|
        \() ->
            Expect.equal
                (Storage.empty
                    |> insert "moons" (Value.int 1)
                    |> getInt "moons"
                )
                (Just 1)
