module VerifyExamples.Storage.Intersect0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#intersect: \n\n    intersect\n        ( fromList [(\"a\", Value.string \"a1\"), (\"c\", Value.string \"c1\")] )\n        ( fromList [(\"a\", Value.string \"a2\"), (\"b2\", Value.string \"b2\")] )\n    --> fromList [ ( \"a\", Value.string \"a1\" )]" <|
        \() ->
            Expect.equal
                (intersect
                    (fromList [ ( "a", Value.string "a1" ), ( "c", Value.string "c1" ) ])
                    (fromList [ ( "a", Value.string "a2" ), ( "b2", Value.string "b2" ) ])
                )
                (fromList [ ( "a", Value.string "a1" ) ])
