module VerifyExamples.Storage.IsEmpty1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec1 : Test.Test
spec1 =
    Test.test "#isEmpty: \n\n    empty\n        |> insert \"fruit\" (Value.string \"apple\")\n        |> isEmpty\n    --> False" <|
        \() ->
            Expect.equal
                (Storage.empty
                    |> insert "fruit" (Value.string "apple")
                    |> isEmpty
                )
                False
