module VerifyExamples.Storage.IsEmpty2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Test


spec2 : Test.Test
spec2 =
    Test.test "#isEmpty: \n\n    isEmpty (fromList [])\n    --> True" <|
        \() ->
            Expect.equal
                (isEmpty (fromList []))
                True
