module VerifyExamples.Storage.ModuleDoc2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value
import Test


configuration : Storage
configuration =
    Storage.fromList
        [ ( "config.item.a", Value.string "some value" )
        , ( "config.item.b", Value.float 1.5 )
        ]


spec2 : Test.Test
spec2 =
    Test.test "Module VerifyExamples: \n\n    Storage.getStringUnsafe \"config.item.b\" configuration\n    --> \"1.5\"" <|
        \() ->
            Expect.equal
                (Storage.getStringUnsafe "config.item.b" configuration)
                "1.5"
