module VerifyExamples.Storage.ModuleDoc0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "Module VerifyExamples: \n\n    empty\n        |> insert \"foo\" (Value.string \"bar\")\n    --> fromList [ ( \"foo\", Value.string \"bar\" ) ]" <|
        \() ->
            Expect.equal
                (Storage.empty
                    |> insert "foo" (Value.string "bar")
                )
                (fromList [ ( "foo", Value.string "bar" ) ])
