module VerifyExamples.Storage.ModuleDoc4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value
import Test


configuration : Storage
configuration =
    Storage.fromList
        [ ( "config.item.a", Value.string "some value" )
        , ( "config.item.b", Value.float 1.5 )
        ]


spec4 : Test.Test
spec4 =
    Test.test "Module VerifyExamples: \n\n    Storage.getString \"config.item.b\" configuration\n    --> Nothing" <|
        \() ->
            Expect.equal
                (Storage.getString "config.item.b" configuration)
                Nothing
