module VerifyExamples.Storage.Singleton0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#singleton: \n\n    singelton \"fruit\" (Value.string \"apple\")\n    --> fromList [ ( \"fruit\", Value.string \"apple\" ) ]" <|
        \() ->
            Expect.equal
                (Storage.singleton "fruit" (Value.string "apple"))
                (fromList [ ( "fruit", Value.string "apple" ) ])
