module VerifyExamples.Storage.ToList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#toList: \n\n    insert \"fruit\" (Value.string \"apple\") empty\n    --> [ ( \"fruit\", Value.string \"apple\" ) ]" <|
        \() ->
            Expect.equal
                (insert "fruit" (Value.string "apple") Storage.empty |> Storage.toList)
                [ ( "fruit", Value.string "apple" ) ]
