module VerifyExamples.Storage.Union0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#union: \n\n    union\n        ( fromList [(\"a\", Value.string \"a1\"), (\"c\", Value.string \"c1\")] )\n        ( fromList [(\"a\", Value.string \"a2\"), (\"b2\", Value.string \"b2\")] )\n    --> fromList (\"a\", Value.string \"a2\"), (\"b2\", Value.string \"b2\"), (\"c\", Value.string \"c1\")]" <|
        \() ->
            Expect.equal
                (union
                    (fromList [ ( "a", Value.string "a1" ), ( "c", Value.string "c1" ) ])
                    (fromList [ ( "a", Value.string "a2" ), ( "b", Value.string "b2" ) ])
                )
                (fromList [ ( "a", Value.string "a1" ), ( "b", Value.string "b2" ), ( "c", Value.string "c1" ) ])
