module VerifyExamples.Storage.Update0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#update: \n\n    empty\n        |> insert \"fruit\" (Value.string \"apple\")\n        |> update \"fruit\" (Maybe.map (\\_ -> Value.string \"banana\"))\n    --> fromList [ ( \"fruit\", Value.string \"banana\" ) ]" <|
        \() ->
            Expect.equal
                (Storage.empty
                    |> insert "fruit" (Value.string "apple")
                    |> update "fruit" (Maybe.map (\_ -> Value.string "banana"))
                )
                (fromList [ ( "fruit", Value.string "banana" ) ])
