module VerifyExamples.Storage.Values0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage exposing (..)
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#values: \n\n    fromList [(\"foo\", Value.string \"a\"), (\"bar\", Value.string \"b\")]\n        |> values\n    --> [Value.string \"b\", Value.string \"a\"]" <|
        \() ->
            Expect.equal
                (fromList [ ( "foo", Value.string "a" ), ( "bar", Value.string "b" ) ]
                    |> values
                )
                [ Value.string "b", Value.string "a" ]
