module VerifyExamples.Storage.Value.ToBool0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#toBool: \n\n    toBool (string \"foo\")\n    --> Nothing" <|
        \() ->
            Expect.equal
                (toBool (string "foo"))
                Nothing
