module VerifyExamples.Storage.Value.ToFloat0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value as Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#toFloat: \n\n    toFloat (int 1)\n    --> Nothing" <|
        \() ->
            Expect.equal
                (Value.toFloat (int 1))
                Nothing
