module VerifyExamples.Storage.Value.ToFloat1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value as Value exposing (..)
import Test


spec1 : Test.Test
spec1 =
    Test.test "#toFloat: \n\n    toFloat (float 1.6  )\n    --> Just 1.6" <|
        \() ->
            Expect.equal
                (Value.toFloat (float 1.6))
                (Just 1.6)
