module VerifyExamples.Storage.Value.ToInt1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value exposing (..)
import Test


spec1 : Test.Test
spec1 =
    Test.test "#toInt: \n\n    toInt (int 1  )\n    --> Just 1" <|
        \() ->
            Expect.equal
                (toInt (int 1))
                (Just 1)
