module VerifyExamples.Storage.Value.ToJson0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#toJson: \n\n    toJson (bool True)\n    --> Nothing" <|
        \() ->
            Expect.equal
                (toJson (bool True))
                Nothing
