module VerifyExamples.Storage.Value.ToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Storage.Value exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toString: \n\n    toString (bool True)\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                toString (bool True)
                )
                (
                Nothing
                )