module VerifyExamples.Storage.Value.ToString1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value exposing (..)
import Test


spec1 : Test.Test
spec1 =
    Test.test "#toString: \n\n    toString (string \"foo\")\n    --> Just \"foo\"" <|
        \() ->
            Expect.equal
                (toString (string "foo"))
                (Just "foo")
