module VerifyExamples.Storage.Value.ToStringUnsafe3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value exposing (..)
import Test


spec3 : Test.Test
spec3 =
    Test.test "#toStringUnsafe: \n\n    toStringUnsafe (float 1.6)\n    --> \"1.6\"" <|
        \() ->
            Expect.equal
                (toStringUnsafe (float 1.6))
                "1.6"
