module VerifyExamples.Storage.Value.ToStringUnsafe1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value exposing (..)
import Test


spec1 : Test.Test
spec1 =
    Test.test "#toStringUnsafe: \n\n    toStringUnsafe (string \"foo\")\n    --> \"foo\"" <|
        \() ->
            Expect.equal
                (toStringUnsafe (string "foo"))
                "foo"
