module VerifyExamples.Storage.Value.ToStringUnsafe5 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value exposing (..)
import Test


spec5 : Test.Test
spec5 =
    Test.test "#toStringUnsafe: \n\n    toStringUnsafe empty\n    --> \"\"" <|
        \() ->
            Expect.equal
                (toStringUnsafe empty)
                ""
