module VerifyExamples.Storage.Value.ToStringUnsafe2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Storage.Value exposing (..)
import Test


spec2 : Test.Test
spec2 =
    Test.test "#toStringUnsafe: \n\n    toStringUnsafe (int 2)\n    --> \"2\"" <|
        \() ->
            Expect.equal
                (toStringUnsafe (int 2))
                "2"
