module VerifyExamples.Storage.Value.ToStringUnsafe0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Json.Encode as Encode
import Storage.Value exposing (..)
import Test


spec0 : Test.Test
spec0 =
    Test.test "#toStringUnsafe: \n\n    toStringUnsafe (json (Encode.object [ (\"foo\", Encode.string \"bar\" ) ]))\n    --> \"{\\\"foo\\\":\\\"bar\\\"}\"" <|
        \() ->
            Expect.equal
                (toStringUnsafe (json (Encode.object [ ( "foo", Encode.string "bar" ) ])))
                "{\"foo\":\"bar\"}"
